# Generated by Django 5.0 on 2024-01-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_faissindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faissindex',
            name='user',
        ),
    ]
