# Generated by Django 5.0 on 2023-12-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aweapp', '0002_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
